### ISSUE TITLE
Staging not deploying

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#81]
```
~/p/hms-weave (staging) $ git push heroku-staging staging:master
Enumerating objects: 57, done.
Counting objects: 100% (57/57), done.
Delta compression using up to 4 threads
Compressing objects: 100% (41/41), done.
Writing objects: 100% (41/41), 9.08 KiB | 1.51 MiB/s, done.
Total 41 (delta 31), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Python app detected
remote: -----> Found python-3.6.7, removing
remote: -----> Installing python-3.6.8
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 2018.5.18…
remote:        Installing dependencies from Pipfile.lock (41a190)…
remote:        An error occurred while installing sentry-sdk==0.7.3; None! Will try again.
remote:        Installing initially–failed dependencies…
remote:
remote:        Exception:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/packaging/markers.py", line 278, in __init__
remote:            self._markers = _coerce_parse_result(MARKER.parseString(marker))
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
remote:            raise exc
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
remote:            loc, tokens = self._parse( instring, 0 )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
remote:            loc, exprtokens = e._parse( instring, loc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
remote:            return self.expr._parse( instring, loc, doActions, callPreParse=False )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
remote:            loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3526, in parseImpl
remote:            raise maxException
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3511, in parseImpl
remote:            ret = e._parse( instring, loc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3698, in parseImpl
remote:            return self.expr._parse( instring, loc, doActions, callPreParse=False )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3359, in parseImpl
remote:            loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3526, in parseImpl
remote:            raise maxException
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3511, in parseImpl
remote:            ret = e._parse( instring, loc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3526, in parseImpl
remote:            raise maxException
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3511, in parseImpl
remote:            ret = e._parse( instring, loc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
remote:            loc,tokens = self.parseImpl( instring, preloc, doActions )
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 2394, in parseImpl
remote:            raise ParseException(instring, loc, self.errmsg, self)
remote:        pip._vendor.pyparsing.ParseException: Expected {Group:({{{"implementation_version" | "platform_python_implementation" | "implementation_name" | "python_full_version" | "platform_release" | "platform_version" | "platform_machine" | "platform_system" | "python_version" | "sys_platform" | "os_name" | "os.name" | "sys.platform" | "platform.version" | "platform.machine" | "platform.python_implementation" | "python_implementation" | "extra"} | {quoted string, starting with ' ending with ' | quoted string, starting with " ending with "}} {"===" | "==" | ">=" | "<=" | "!=" | "~=" | ">" | "<" | "not in" | "in"} {{"implementation_version" | "platform_python_implementation" | "implementation_name" | "python_full_version" | "platform_release" | "platform_version" | "platform_machine" | "platform_system" | "python_version" | "sys_platform" | "os_name" | "os.name" | "sys.platform" | "platform.version" | "platform.machine" | "platform.python_implementation" | "python_implementation" | "extra"} | {quoted string, starting with ' ending with ' | quoted string, starting with " ending with "}}}) | Group:({Suppress:("(") Forward: ... Suppress:(")")})} (at char 0), (line:1, col:1)
remote:
remote:        During handling of the above exception, another exception occurred:
remote:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
remote:            status = self.run(options, args)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/commands/install.py", line 312, in run
remote:            wheel_cache
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
remote:            wheel_cache=wheel_cache):
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_file.py", line 93, in parse_requirements
remote:            for req in req_iter:
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_file.py", line 158, in process_line
remote:            isolated=isolated, options=req_options, wheel_cache=wheel_cache
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/req/req_install.py", line 182, in from_line
remote:            markers = Marker(markers)
remote:          File "/app/.heroku/python/lib/python3.6/site-packages/pip/_vendor/packaging/markers.py", line 282, in __init__
remote:            raise InvalidMarker(err_str)
remote:        pip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'None', parse error at 'None'
remote:        You are using pip version 9.0.2, however version 19.0.3 is available.
remote:        You should consider upgrading via the 'pip install --upgrade pip' command.
remote:
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to hms-weave-staging.
remote:
To https://git.heroku.com/hms-weave-staging.git
 ! [remote rejected] staging -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/hms-weave-staging.git'
```

**Comment by razzius** [comment]
Upgrading pipenv, pip, and pinning sentry-sdk locally fixed it.

```
pip install -U pip
pip install -U pipenv
pipenv install 'sentry-sdk[flask]==0.7.4'
```
